use automexia_keybindings::{
    action_schemas, adapt_for_windows, bundled_profile, compile,
    ghostty_1_3_linux_provenance, PlatformFamily, ProfileId, GHOSTTY_1_3_COMMIT,
    GHOSTTY_1_3_PATCH,
};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use super::{root, run, TaskResult};

const VERSION: &str = "1.3.1";
const GENERATOR_SCHEMA: u32 = 1;
const BENCHMARK_SCHEMA: u32 = 1;
const QA_BUNDLE_SCHEMA: u32 = 1;
const SNAPSHOT_SCHEMA: u32 = 1;

pub(super) fn generate(args: &[String]) -> TaskResult {
    match args {
        [flag, version] if flag == "--version" && version == VERSION => {
            write_outputs(&artifact_root(), &generated_outputs()?)?;
            write_outputs(&reference_root(), &generated_references()?)?;
            println!("PASS: generated Ghostty {VERSION} keybinding artifacts and references");
            Ok(())
        }
        [flag] if flag == "--check" => verify(),
        [flag, version] if flag == "--version" => Err(format!(
            "unsupported Ghostty fixture version '{version}'; bundled version is {VERSION}"
        )),
        _ => Err(
            "usage: cargo xtask generate keybindings <--version 1.3.1|--check>"
                .into(),
        ),
    }
}

pub(super) fn verify() -> TaskResult {
    verify_outputs(&artifact_root(), generated_outputs()?, "artifact")?;
    verify_outputs(&reference_root(), generated_references()?, "reference")?;
    println!("PASS: Ghostty {VERSION} keybinding artifacts, checksums, and references are current");
    Ok(())
}

fn verify_outputs(
    destination: &Path,
    expected: BTreeMap<String, Vec<u8>>,
    kind: &str,
) -> TaskResult {
    for (name, bytes) in expected {
        let path = destination.join(&name);
        let actual = fs::read(&path).map_err(|error| {
            format!("missing generated keybinding {kind} {name}: {error}")
        })?;
        if actual != bytes {
            return Err(format!(
                "generated keybinding {kind} {name} is stale; run cargo xtask generate keybindings --version {VERSION}"
            ));
        }
    }
    Ok(())
}

pub(super) fn test() -> TaskResult {
    run(
        "cargo",
        &["test", "-p", "automexia-keybindings", "--locked"],
    )?;
    for filter in [
        "bindings::registry::tests",
        "renderer::command_palette::tests",
        "renderer::compatibility_inspector::tests",
        "screen::compatibility::tests",
        "automexia::export::tests",
        "automexia::ghostty_migration::tests",
        "layout::pane_tab_tests::split_zoom",
        "layout::pane_tab_tests::equalization",
        "context::test::parked_topology",
    ] {
        run(
            "cargo",
            &["test", "-p", "automexia-terminal", "--locked", filter],
        )?;
    }
    run(
        "cargo",
        &[
            "test",
            "-p",
            "rio-vt",
            "--locked",
            "bounded_selection_serialization_rejects_before_copying_oversize_text",
        ],
    )?;
    verify()
}

fn artifact_root() -> PathBuf {
    root()
        .join("tests")
        .join("fixtures")
        .join("keybindings")
        .join("ghostty")
        .join(VERSION)
}

fn reference_root() -> PathBuf {
    root().join("docs").join("generated")
}

fn generated_references() -> TaskResult<BTreeMap<String, Vec<u8>>> {
    use std::fmt::Write as _;

    let linux_specs = bundled_profile(ProfileId::Ghostty13, PlatformFamily::LinuxBsd)
        .map_err(str::to_string)?;
    let linux = compile(&linux_specs)
        .registry
        .ok_or_else(|| "bundled Linux fixture no longer compiles".to_string())?;
    let windows = compile(&adapt_for_windows(&linux_specs).bindings)
        .registry
        .ok_or_else(|| {
            "deterministic Windows adaptation no longer compiles".to_string()
        })?;

    let mut bindings = String::from(
        "<!-- Generated by `cargo xtask generate keybindings --version 1.3.1`; do not edit. -->\n\n# Ghostty 1.3 keybindings\n\nThe Linux/BSD rows are normalized from the pinned Ghostty 1.3.1 binary. Windows rows are Automexia's documented deterministic adaptation. A native macOS table is intentionally absent until the external generation gate passes.\n\n| Platform | Trigger | Action | Origin | Scope | Policy |\n|---|---|---|---|---|---|\n",
    );
    for (platform, registry) in [("Linux/BSD", &linux), ("Windows adapted", &windows)] {
        for binding in registry.bindings() {
            let policy = format!(
                "{:?}{}",
                binding.policy.consumption,
                if binding.policy.performable {
                    ", performable"
                } else {
                    ""
                }
            )
            .to_ascii_lowercase();
            writeln!(
                bindings,
                "| {platform} | `{}` | `{}` | `{:?}` | `{:?}` | `{policy}` |",
                markdown_cell(&binding.trigger_label()),
                markdown_cell(&binding.action_label()),
                binding.origin,
                binding.scope,
            )
            .map_err(|_| "could not generate binding reference".to_string())?;
        }
    }

    let mut actions = String::from(
        "<!-- Generated by `cargo xtask generate keybindings --version 1.3.1`; do not edit. -->\n\n# Ghostty 1.3 action support\n\nUnsupported and deprecated actions remain discoverable but fail closed in strict mode. `Adapted` means Automexia preserves the intent with a documented platform or lifecycle limitation.\n\n| Action ID | Aliases | Parameter | Capability | Support |\n|---|---|---|---|---|\n",
    );
    for schema in action_schemas() {
        writeln!(
            actions,
            "| `{}` | {} | `{:?}` | `{:?}` | `{:?}` |",
            schema.id,
            if schema.aliases.is_empty() {
                "—".to_string()
            } else {
                schema
                    .aliases
                    .iter()
                    .map(|alias| format!("`{}`", markdown_cell(alias)))
                    .collect::<Vec<_>>()
                    .join(", ")
            },
            schema.parameter,
            schema.capability,
            schema.support,
        )
        .map_err(|_| "could not generate action reference".to_string())?;
    }

    Ok(BTreeMap::from([
        ("ghostty-1.3-keybindings.md".into(), bindings.into_bytes()),
        ("ghostty-1.3-actions.md".into(), actions.into_bytes()),
    ]))
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn generated_outputs() -> TaskResult<BTreeMap<String, Vec<u8>>> {
    generated_outputs_with_classic(classic_manifest)
}

fn generated_outputs_with_classic<F>(
    mut load_classic: F,
) -> TaskResult<BTreeMap<String, Vec<u8>>>
where
    F: FnMut() -> TaskResult<Vec<u8>>,
{
    let linux_specs = bundled_profile(ProfileId::Ghostty13, PlatformFamily::LinuxBsd)
        .map_err(str::to_string)?;
    let linux_report = compile(&linux_specs);
    let linux = linux_report
        .registry
        .ok_or_else(|| "bundled Linux fixture no longer compiles".to_string())?;
    let windows_adaptation = adapt_for_windows(&linux_specs);
    let windows_report = compile(&windows_adaptation.bindings);
    let windows = windows_report.registry.ok_or_else(|| {
        "deterministic Windows adaptation no longer compiles".to_string()
    })?;
    let provenance = ghostty_1_3_linux_provenance()
        .map_err(|error| format!("invalid bundled provenance: {error}"))?;

    let mut outputs = BTreeMap::new();
    insert_json(
        &mut outputs,
        "linux.json",
        &json!({
            "schema_version": automexia_keybindings::SCHEMA_VERSION,
            "profile": "ghostty-1.3",
            "platform": "linux_bsd",
            "upstream_patch": GHOSTTY_1_3_PATCH,
            "upstream_commit": GHOSTTY_1_3_COMMIT,
            "bindings": linux.bindings().collect::<Vec<_>>(),
            "diagnostics": linux_report.diagnostics,
            "stats": linux.stats(),
        }),
    )?;
    insert_json(
        &mut outputs,
        "windows-adapted.json",
        &json!({
            "schema_version": automexia_keybindings::SCHEMA_VERSION,
            "profile": "ghostty-1.3",
            "platform": "windows_adapted",
            "upstream_platform": "linux_bsd",
            "bindings": windows.bindings().collect::<Vec<_>>(),
            "diagnostics": windows_report.diagnostics,
            "stats": windows.stats(),
        }),
    )?;
    insert_json(
        &mut outputs,
        "actions.json",
        &json!({
            "schema_version": automexia_keybindings::SCHEMA_VERSION,
            "upstream_patch": GHOSTTY_1_3_PATCH,
            "actions": action_schemas(),
        }),
    )?;
    insert_json(
        &mut outputs,
        "provenance.json",
        &json!({
            "schema_version": GENERATOR_SCHEMA,
            "upstream": provenance,
            "schemas": {
                "registry": automexia_keybindings::SCHEMA_VERSION,
                "generator": GENERATOR_SCHEMA,
                "snapshot": SNAPSHOT_SCHEMA,
                "benchmark": BENCHMARK_SCHEMA,
                "qa_bundle": QA_BUNDLE_SCHEMA,
            },
            "normal_ci": {
                "network": false,
                "external_ghostty_process": false,
            },
            "macos_fixture": {
                "status": "external_prerequisite",
                "reason": "requires a native macOS Ghostty 1.3.1 generation and smoke runner"
            }
        }),
    )?;
    insert_json(
        &mut outputs,
        "deviations.json",
        &json!({
            "schema_version": GENERATOR_SCHEMA,
            "automexia": [{
                "code": "font_range_clamped",
                "actions": [
                    "increase_font_size",
                    "decrease_font_size",
                    "set_font_size"
                ],
                "upstream_points": "1..=255",
                "automexia_points": "6..=100",
                "reason": "preserves Automexia's reviewed readable renderer range"
            }],
            "windows": windows_adaptation.diagnostics,
            "rules": [
                "super_is_the_windows_key",
                "primary_selection_uses_clipboard",
                "unsupported_globals_are_omitted",
                "os_intercepted_combinations_are_diagnostic"
            ],
            "macos": {
                "status": "external_prerequisite",
                "not_synthesized": true
            }
        }),
    )?;
    if cfg!(windows) {
        outputs.insert("automexia-classic-windows.json".into(), load_classic()?);
    }

    let checksums = outputs
        .iter()
        .map(|(name, bytes)| {
            (
                name.clone(),
                json!({ "sha256": sha256(bytes), "bytes": bytes.len() }),
            )
        })
        .collect::<serde_json::Map<_, _>>();
    insert_json(
        &mut outputs,
        "manifest.json",
        &json!({
            "schema_version": GENERATOR_SCHEMA,
            "version": VERSION,
            "artifacts": checksums,
        }),
    )?;
    Ok(outputs)
}

fn classic_manifest() -> TaskResult<Vec<u8>> {
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = Command::new(cargo)
        .current_dir(root())
        .args([
            "run",
            "-q",
            "-p",
            "automexia-terminal",
            "--locked",
            "--",
            "--list-keybinds",
            "--profile",
            "automexia",
            "--platform",
            "windows",
            "--json",
        ])
        .output()
        .map_err(|error| format!("could not generate classic manifest: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "classic manifest command failed: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let value: Value = serde_json::from_slice(&output.stdout)
        .map_err(|error| format!("classic manifest output was invalid: {error}"))?;
    pretty_json(&value)
}

fn insert_json(
    outputs: &mut BTreeMap<String, Vec<u8>>,
    name: &str,
    value: &Value,
) -> TaskResult {
    outputs.insert(name.into(), pretty_json(value)?);
    Ok(())
}

fn pretty_json(value: &Value) -> TaskResult<Vec<u8>> {
    let mut bytes = serde_json::to_vec_pretty(value)
        .map_err(|error| format!("could not serialize generated artifact: {error}"))?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn sha256(bytes: &[u8]) -> String {
    use std::fmt::Write as _;

    let mut output = String::with_capacity(64);
    for byte in Sha256::digest(bytes) {
        write!(&mut output, "{byte:02x}").expect("writing to String cannot fail");
    }
    output
}

fn write_outputs(destination: &Path, outputs: &BTreeMap<String, Vec<u8>>) -> TaskResult {
    fs::create_dir_all(destination).map_err(|error| {
        format!("could not create {}: {error}", destination.display())
    })?;
    for (name, bytes) in outputs {
        let path = destination.join(name);
        fs::write(&path, bytes)
            .map_err(|error| format!("could not write {}: {error}", path.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generated_outputs_for_test() -> TaskResult<BTreeMap<String, Vec<u8>>> {
        generated_outputs_with_classic(|| {
            fs::read(artifact_root().join("automexia-classic-windows.json"))
                .map_err(|error| format!("could not read checked fixture: {error}"))
        })
    }

    #[test]
    fn generated_references_are_registry_owned_and_redacted() {
        let references = generated_references().unwrap();
        let bindings =
            std::str::from_utf8(&references["ghostty-1.3-keybindings.md"]).unwrap();
        let actions = std::str::from_utf8(&references["ghostty-1.3-actions.md"]).unwrap();
        assert!(bindings.contains("| Linux/BSD | `ctrl+shift+t` | `new_tab`"));
        assert!(bindings.contains("| Windows adapted |"));
        assert!(bindings.contains("native macOS table is intentionally absent"));
        assert!(actions.contains("| `close_all_windows` |"));
        assert!(actions.contains("`DeprecatedUnsafe`"));
        assert!(!bindings.contains("USERPROFILE"));
        assert!(!actions.contains("clipboard contents"));
    }

    #[test]
    fn deviations_record_the_cross_platform_font_range_adaptation() {
        let outputs = generated_outputs_for_test().unwrap();
        let deviations: Value =
            serde_json::from_slice(&outputs["deviations.json"]).unwrap();
        let font = &deviations["automexia"][0];
        assert_eq!(font["code"], "font_range_clamped");
        assert_eq!(font["upstream_points"], "1..=255");
        assert_eq!(font["automexia_points"], "6..=100");
        assert_eq!(
            font["actions"],
            json!(["increase_font_size", "decrease_font_size", "set_font_size"])
        );
    }

    #[test]
    fn manifest_hashes_every_generated_pre_manifest_artifact() {
        let outputs = generated_outputs_for_test().unwrap();
        let manifest: Value = serde_json::from_slice(&outputs["manifest.json"]).unwrap();
        let artifacts = manifest["artifacts"].as_object().unwrap();
        assert_eq!(artifacts.len() + 1, outputs.len());
        for (name, value) in artifacts {
            assert_eq!(value["sha256"], sha256(&outputs[name]));
        }
    }
}
