version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      cargo-production:
        dependency-type: production
      cargo-development:
        dependency-type: development
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns: ['*']
    open-pull-requests-limit: 5
