# Arctic Day - Automexia built-in palette
# Copy this theme to customize it.
[colors]
background = "#f2f6fa"
foreground = "#253744"
dim-foreground = "#536778"
cursor = "#266d99"
vi-cursor = "#68318d"
tabs = "#e4edf4"
tabs-active = "#d2e7f5"
selection-background = "#d2e7f5"
selection-foreground = "#253744"
split = "#e4edf4"
split-active = "#266d99"
search-match-background = "#d2e7f5"
search-match-foreground = "#253744"
search-focused-match-background = "#80570e"
search-focused-match-foreground = "#f2f6fa"
hint-background = "#176477"
hint-foreground = "#f2f6fa"
black = "#263945"
red = "#ad334b"
green = "#22694a"
yellow = "#80570e"
blue = "#295f9b"
magenta = "#764299"
cyan = "#176477"
white = "#d7e1e8"
light-black = "#536c7c"
light-red = "#98243b"
light-green = "#145c3c"
light-yellow = "#735000"
light-blue = "#1c528d"
light-magenta = "#68318d"
light-cyan = "#07576c"
light-white = "#ffffff"
