# Arctic Glass - Automexia built-in palette
# Copy this theme to customize it.
[colors]
background = "#101c27"
foreground = "#e4edf4"
dim-foreground = "#a3b6c5"
cursor = "#a4dff1"
vi-cursor = "#e5d8fb"
tabs = "#172a38"
tabs-active = "#2c495d"
selection-background = "#2c495d"
selection-foreground = "#e4edf4"
split = "#172a38"
split-active = "#a4dff1"
search-match-background = "#2c495d"
search-match-foreground = "#e4edf4"
search-focused-match-background = "#ead49e"
search-focused-match-foreground = "#101c27"
hint-background = "#8edbed"
hint-foreground = "#101c27"
black = "#253a4a"
red = "#f693a1"
green = "#a4d8bd"
yellow = "#ead49e"
blue = "#9cc4ed"
magenta = "#cbb9eb"
cyan = "#8edbed"
white = "#c6d8e5"
light-black = "#607d91"
light-red = "#ffb8c0"
light-green = "#c9ead7"
light-yellow = "#f8e6bc"
light-blue = "#c4def9"
light-magenta = "#e5d8fb"
light-cyan = "#bcf1fc"
light-white = "#f6fbff"
