# Aurora Night - Automexia built-in palette
# Copy this theme to customize it.
[colors]
background = "#081024"
foreground = "#dfe8ff"
dim-foreground = "#94a5ca"
cursor = "#63ceff"
vi-cursor = "#ddbeff"
tabs = "#09172b"
tabs-active = "#192b50"
selection-background = "#192b50"
selection-foreground = "#dfe8ff"
split = "#09172b"
split-active = "#63ceff"
search-match-background = "#192b50"
search-match-foreground = "#dfe8ff"
search-focused-match-background = "#f3d283"
search-focused-match-foreground = "#081024"
hint-background = "#59dfff"
hint-foreground = "#081024"
black = "#142440"
red = "#ff759b"
green = "#69dfb1"
yellow = "#f3d283"
blue = "#70adff"
magenta = "#c797ff"
cyan = "#59dfff"
white = "#c3d3ed"
light-black = "#485e86"
light-red = "#ff9ab5"
light-green = "#95eac6"
light-yellow = "#ffe6a6"
light-blue = "#a2caff"
light-magenta = "#ddbeff"
light-cyan = "#a1edff"
light-white = "#f4f7ff"
