# Forest Operator - Automexia built-in palette
# Copy this theme to customize it.
[colors]
background = "#061b16"
foreground = "#ddf2e6"
dim-foreground = "#96b6a6"
cursor = "#69e5b3"
vi-cursor = "#e3ccfa"
tabs = "#96b6a6"
tabs-active = "#ddf2e6"
selection-background = "#184e38"
selection-foreground = "#ddf2e6"
split = "#0b251d"
split-active = "#69e5b3"
search-match-background = "#184e38"
search-match-foreground = "#ddf2e6"
search-focused-match-background = "#e3d574"
search-focused-match-foreground = "#061b16"
hint-background = "#70e0d1"
hint-foreground = "#061b16"
black = "#153b2c"
red = "#f98891"
green = "#68e7a2"
yellow = "#e3d574"
blue = "#91bbf5"
magenta = "#ceadf1"
cyan = "#70e0d1"
white = "#c7ddd1"
light-black = "#4b7763"
light-red = "#ffb0b6"
light-green = "#a0f2c0"
light-yellow = "#f1e5a0"
light-blue = "#bad4fc"
light-magenta = "#e3ccfa"
light-cyan = "#a8f0e5"
light-white = "#f2fff6"
