# Solar Dusk - Automexia built-in palette
# Copy this theme to customize it.
[colors]
background = "#19120f"
foreground = "#f2e6d8"
dim-foreground = "#bca697"
cursor = "#ffc276"
vi-cursor = "#e9c7ec"
tabs = "#bca697"
tabs-active = "#f2e6d8"
selection-background = "#4d3626"
selection-foreground = "#f2e6d8"
split = "#241a14"
split-active = "#ffc276"
search-match-background = "#4d3626"
search-match-foreground = "#f2e6d8"
search-focused-match-background = "#f2bf6c"
search-focused-match-foreground = "#19120f"
hint-background = "#90d3c5"
hint-foreground = "#19120f"
black = "#38291f"
red = "#ff867b"
green = "#b9d887"
yellow = "#f2bf6c"
blue = "#99bcea"
magenta = "#d6a4d9"
cyan = "#90d3c5"
white = "#ddcbb8"
light-black = "#786354"
light-red = "#ffb1a4"
light-green = "#d1e6a7"
light-yellow = "#ffdaa1"
light-blue = "#bdd4f4"
light-magenta = "#e9c7ec"
light-cyan = "#b9e7db"
light-white = "#fff4e7"
