name: Release Drafter
on:
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: read
jobs:
  update:
    runs-on: ubuntu-24.04
    steps:
    - uses: 
        release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 15
concurrency:
  group: release-drafter
  cancel-in-progress: true
